name: dpn_py3
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- ncurses=5.9=10
- openssl=1.0.2l=0
- pip=9.0.1=py36_0
- python=3.6.3=0
- readline=6.2=0
- setuptools=36.6.0=py36_1
- sqlite=3.13.0=1
- tk=8.5.19=2
- wheel=0.30.0=py_1
- xz=5.2.3=0
- zlib=1.2.8=3
- pip:
  - isodate==0.6.0
  - lxml==4.1.0
  - pyparsing==2.2.0
  - rdflib==4.2.2
  - six==1.11.0
  - xmltodict=0.11.0
